name: Chat 
on: [push, workflow_dispatch]
jobs:
  meet:
    runs-on: ubuntu-latest
    steps:
    - name: Google Chat Notification
      uses: tarcionicos/main@master
      with:
        name: Build
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        status: ${{ job.status }}
      if: always()
      continue-on-error: true